### ISSUE TITLE
Markdown to html parser

### ISSUE THREAD

**Issue by leonpolak** [Metaserverless/Console#16]
\application\static\client\experiments\markdowntohtml.html

Несмотря на то, что существуют повсеместно используемые npm пакеты для этих целей, есть мнение, что можно сделать своё проверенное и эффестивное средства конвертации md в html без такого количества настроек, а просто реверс инженирингом [гитхабовского парсера](https://docs.github.com/en/rest/markdown). Собственно, в этом файле первые попытки сделать что-то подобное (и заодно рядом проверки на библиотеках marked и showdown, для сравнения). Конечный результат должен выглядеть как [здесь](https://github.com/metarhia/ExampleWebSite/blob/main/application/resources/content/index.en.md) (для этого в файл скопирован html и стили с гитхаба).

Основные требования к алгоритму: чтоб работал быстро, то есть, максимально избегать использования регулярных выражений, и результат был-бы аналогичный распространённым библиотекам. Ну и, соответственно, вот[ этой спецификации](https://github.github.com/gfm/#characters-and-lines).,

**Comment by ArtificialMan3000** [comment]
Я возьму это

**Comment by ArtificialMan3000** [comment]
See issue https://github.com/metarhia/metacms/issues/2 in metacms repo.
