### ISSUE TITLE
Многоуровневое верхнее меню

### ISSUE THREAD

**Issue by leonpolak** [Metaserverless/Console#20]
Довольно простое задание.

В файле /static/client/elements/Topmenu.js лежит класс управляющий верхним меню, пункты для которого заданы в /static/client/controllers/controller_topheader.js. Надо сделать так, чтоб дерево подэлементов меню было многомерным, то есть сейчас открывается только один элемент меню, а хотелось бы чтобы к каждой строке можно было добавлять элементы открывающиеся вбок. Все css стили находятся в файле /static/client/index.css

**Comment by vitalii88** [comment]
готов взяться за это задание

**Comment by roman-serebrov** [comment]
готов тоже попробовать сделать, как раз разберусь и смогу в дольнейшем быстрей помогать!

**Comment by leonpolak** [comment]
в /static/client/controllers/controller_topheader.js на 17й строке лежит эррэй this.items на основе которого Topmenu.js в конструкторе генерирует html. Предмтавьте себе, что в третьем элементе эррэя на 147 строке, в объект выглядит так: в первsq элемент выглядит так: 

```
 {
        title: 'View',
        items: [
{
          title: 'Placeholder',
          action: 'placeholder',
          shortcut: 'Ctrl+Shift+P',
          items: [{
               title: 'Placeholder 2',
               action: 'placeholder 2',
                shortcut: 'Ctrl+Shift+P',
            },
           {
              title: 'Placeholder 3',
              action: 'placeholder 3',
               shortcut: 'Ctrl+Shift+P',
           }]

        }]
}
```

Первое меню c одной строкой открывается на mouseover вниз, а на mouseover первой строки открывшегося меню  - открывается подмею вбок с двума строками

**Comment by roman-serebrov** [comment]
я уже реализовал открытие под меню. Завтра немного код под рефакторю и отправлю Вам посмотреть.

**Comment by roman-serebrov** [comment]
![Снимок экрана 2022-07-24 в 23 10 10](https://user-images.githubusercontent.com/68200207/180664105-68e4c44e-036c-45e5-a57f-aa3d859eb46b.png)

на данный момент, как пример, это выглядит вот так!правильно я понял задание?

**Comment by leonpolak** [comment]
> на данный момент, как пример, это выглядит вот так!правильно я понял задание?

Да, всё именно так. Только сделайте, плиз подменю фиксированной минимальной ширины, как родительское.

**Comment by roman-serebrov** [comment]
Leon good afternoon! Haven't looked at the last commit?

**Comment by leonpolak** [comment]
Это нужно было сделать вот так:
