### ISSUE TITLE
Стилизация контекстного меню

### ISSUE THREAD

**Issue by leonpolak** [Metaserverless/Console#23]
Нужно добавить стили, показывающие контекстное меню (по правому клику на дереве) так, чтобы оно выглядело похожим на выпадающие списки верхнего меню и вообще на остальной дизайн. Чисто поиграть с css.

**Comment by darv86** [comment]
Готов взять эту задачу

**Comment by leonpolak** [comment]
В index.css в строках 358-387 мои попытки это сделать, но тогда были более срочные дела, и я 
 это закомментировал. Посмотрите в консоле хрома какие там элементы и имена классов в меню и переопределите их в index.css так, чтобы было похоже на остальное.

**Comment by leonpolak** [comment]
Great job
